#!/bin/bash

if [[ "$CI" != 'true' ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator10.3'
    export WORKSPACE='RxSwift-Demo.xcworkspace'
    export DESTINATION='OS=10.3.1,name=iPhone 7'
    export CONFIGURATION='Debug'
fi

export SCHEME='RxSwift-Demo'

rm -rf ./build

xcodebuild build \
    -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration "$CONFIGURATION" | bundle exec xcpretty;

exit "${PIPESTATUS[0]}"
